<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <!--cabecalho, serve pro Maven reconhecer como pom valido-->

  <groupId>com.twinig</groupId>
  <artifactId>gerenciador-torneio</artifactId>
  <version>1.0.0</version>
  <packaging>jar</packaging>
  <!--indentificação do projeto, com nome, versão, formato de saida jar-->

  <properties>
    <maven.compiler.source>25</maven.compiler.source>
    <maven.compiler.target>25</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
    <!--Propriedades, indentificam a versao do java e o sourceEncoding evita erros de gramatica-->
  <dependencies>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.11.0</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.10.2</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <!--dependencias de biblioteca que o projeto usa, como gson, que converte json em objetos java e o JUnit 5, framework de testes automatizados, pra evitar erros ne-->

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.2.5</version>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.2.0</version>
        <configuration>
          <mainClass>com.twinig.torneio.Main</mainClass>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
<!--Plugins sao outras ferramentas extras, como surefire que executa testes JUnit e exec que permite rodar o programa com mvn exec:java-->
<!--Toda essa ladainha porque o Maven depende desse arquivo pra compilar, testar e colocar os resultados-->